---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: centos-stream8
    image: quay.io/centos/centos:stream8
    pre_build_image: true
  - name: oraclelinux8
    image: docker.io/dokken/oraclelinux-8
    pre_build_image: true
  - name: ubuntu-latest
    image: docker.io/ubuntu:latest
    per_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
