---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: ubuntu-latest
    image: docker.io/ubuntu:latest
    per_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario: 
  test_sequence:
    - destroy
    - create
    - converge
    - destroy
